/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as ProfileCreateRouteImport } from './routes/profile.create'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminRolesRouteImport } from './routes/_admin/admin.roles'
import { Route as AdminAdminRidersRouteImport } from './routes/_admin/admin.riders'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin/admin.orders'
import { Route as AdminAdminRidersIdRouteImport } from './routes/_admin/admin.riders.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCreateRoute = ProfileCreateRouteImport.update({
  id: '/profile/create',
  path: '/profile/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRolesRoute = AdminAdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRidersRoute = AdminAdminRidersRouteImport.update({
  id: '/admin/riders',
  path: '/admin/riders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRidersIdRoute = AdminAdminRidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminRidersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/profile/create': typeof ProfileCreateRoute
  '/r/$slug': typeof RSlugRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/riders': typeof AdminAdminRidersRouteWithChildren
  '/admin/roles': typeof AdminAdminRolesRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/riders/$id': typeof AdminAdminRidersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/profile/create': typeof ProfileCreateRoute
  '/r/$slug': typeof RSlugRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/admin/riders': typeof AdminAdminRidersRouteWithChildren
  '/admin/roles': typeof AdminAdminRolesRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/riders/$id': typeof AdminAdminRidersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/profile/create': typeof ProfileCreateRoute
  '/r/$slug': typeof RSlugRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
  '/_admin/admin/riders': typeof AdminAdminRidersRouteWithChildren
  '/_admin/admin/roles': typeof AdminAdminRolesRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/riders/$id': typeof AdminAdminRidersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/profile/create'
    | '/r/$slug'
    | '/admin/orders'
    | '/admin/riders'
    | '/admin/roles'
    | '/admin/'
    | '/admin/riders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/profile/create'
    | '/r/$slug'
    | '/admin/orders'
    | '/admin/riders'
    | '/admin/roles'
    | '/admin'
    | '/admin/riders/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/profile/create'
    | '/r/$slug'
    | '/_admin/admin/orders'
    | '/_admin/admin/riders'
    | '/_admin/admin/roles'
    | '/_admin/admin/'
    | '/_admin/admin/riders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ProfileCreateRoute: typeof ProfileCreateRoute
  RSlugRoute: typeof RSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/create': {
      id: '/profile/create'
      path: '/profile/create'
      fullPath: '/profile/create'
      preLoaderRoute: typeof ProfileCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/roles': {
      id: '/_admin/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminAdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/riders': {
      id: '/_admin/admin/riders'
      path: '/admin/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminAdminRidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/riders/$id': {
      id: '/_admin/admin/riders/$id'
      path: '/$id'
      fullPath: '/admin/riders/$id'
      preLoaderRoute: typeof AdminAdminRidersIdRouteImport
      parentRoute: typeof AdminAdminRidersRoute
    }
  }
}

interface AdminAdminRidersRouteChildren {
  AdminAdminRidersIdRoute: typeof AdminAdminRidersIdRoute
}

const AdminAdminRidersRouteChildren: AdminAdminRidersRouteChildren = {
  AdminAdminRidersIdRoute: AdminAdminRidersIdRoute,
}

const AdminAdminRidersRouteWithChildren =
  AdminAdminRidersRoute._addFileChildren(AdminAdminRidersRouteChildren)

interface AdminRouteChildren {
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
  AdminAdminRidersRoute: typeof AdminAdminRidersRouteWithChildren
  AdminAdminRolesRoute: typeof AdminAdminRolesRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
  AdminAdminRidersRoute: AdminAdminRidersRouteWithChildren,
  AdminAdminRolesRoute: AdminAdminRolesRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ProfileCreateRoute: ProfileCreateRoute,
  RSlugRoute: RSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
